### ISSUE TITLE
HTTPError: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by FangJingYunner** [civat/DL-Theory-Practice#1]
帅哥，我运行代码的时候遇到这个报错咋解决呀？
```
Traceback (most recent call last):
  File "/home/fjy/Desktop/py_ws/DL-Theory-Practice/trainer_classification.py", line 51, in <module>
    trn_data = datasets.CIFAR10(root=configs["Dataset"]["root_path"], train=True, transform=trn_trans, download=True)
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/site-packages/torchvision/datasets/cifar.py", line 65, in __init__
    self.download()
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/site-packages/torchvision/datasets/cifar.py", line 143, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 256, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 81, in download_url
    reporthook=gen_bar_updater()
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/fjy/anaconda3/envs/torch17/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
0it [00:02, ?it/s]
0it [00:00, ?it/s]

Process finished with exit code 1
```

**Comment by FangJingYunner** [comment]
第二次运行又好了，数据集下载下来了。但是代码跑起来好像有bug
```
2022-09-22 11:10:26,528 - INFO - Computational complexity:       15.87 MMac
INFO:../workspace/Output/Classification/MobileOne/MobileOne_20_CIFAR10_EXP/train.log:Computational complexity:       15.87 MMac
2022-09-22 11:10:26,528 - INFO - Number of parameters    :       48.39 k 
INFO:../workspace/Output/Classification/MobileOne/MobileOne_20_CIFAR10_EXP/train.log:Number of parameters    :       48.39 k 
Traceback (most recent call last):
  File "/home/fjy/Desktop/py_ws/DL-Theory-Practice/trainer_classification.py", line 127, in <module>
    scheduler = utils.get_scheduler(optimizer, configs["Model"]["Scheduler"])
  File "/home/fjy/Desktop/py_ws/DL-Theory-Practice/classification/utils.py", line 64, in get_scheduler
    schedulers.append(schedulers_available[key](optimizer, **scheduler_configs[key]))
KeyError: 'ConstantLR'
```
我的pytorch是1.7.1的，是不是版本太低了

**Comment by civat** [comment]
版本问题，1.7.1不支持ConstantLR。你可以把你跑的config文件里面的ConstantLR删掉即可。
